### ISSUE TITLE
TODO: DB-related stuff

### ISSUE THREAD

**Issue by HAOYUatHZ** [Fluidex/prover-cluster#26]
+ [x] sqlxverf (https://github.com/Fluidex/prover-cluster/pull/30)
+ [x] define schema (https://github.com/Fluidex/prover-cluster/pull/32)
+ [x] migrate (https://github.com/Fluidex/prover-cluster/pull/33)
